// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiTXT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230629021123_Create_Table_TXTCau3")]
    partial class Create_Table_TXTCau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaiThiTXT.Models.TXTCau3", b =>
                {
                    b.Property<int?>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KhoaHoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("TXTCau3");
                });
#pragma warning restore 612, 618
        }
    }
}
